fixed the typo errors
LearnWeb3DAO/Junior-Track pull request #24
Opened 2023-02-26 15:31 UTC by jitendragangwar123

I have fixed the typo errors. Please review and merge it

2023-02-27 12:54 UTC, yanukadeneth99 requested changes

2023-02-27 12:54 UTC, yanukadeneth99 commented on Lottery-Game-Chainlink-VRF.md
> +- Smart contract can then use this data to make a decision and change it's state.
This should be `its`. You can find more [here](https://www.grammarly.com/blog/its-vs-its/).

2023-02-27 12:54 UTC, yanukadeneth99 commented on Lottery-Game-Chainlink-VRF.md
> +- However it is important to note that the blockchain oracle is not itself the data source but it's job is to query, verify and authenticate the outside data and then further pass it to the smart con
This should be `its`. You can find more [here](https://www.grammarly.com/blog/its-vs-its/).

2023-02-27 12:54 UTC, yanukadeneth99 commented on Lottery-Game-Chainlink-VRF.md
> +- `linkToken` is the address of the link token which is the token in which the chainlink takes it's payment
This should be `its`. You can find more [here](https://www.grammarly.com/blog/its-vs-its/).

2023-02-27 12:54 UTC, yanukadeneth99 commented on Lottery-Game-Chainlink-VRF.md
> +This function was inherited from `VRFConsumerBase`. It is called by `VRFCoordinator` contract after it receives the randomness from the external world. After receiving the randomness which can be any
This should be `its`. You can find more [here](https://www.grammarly.com/blog/its-vs-its/).

2023-02-27 16:10 UTC, jitendragangwar123 commented
I have updated the file according to the given suggestions. Please review and merge it.

2023-02-28 17:55 UTC, yanukadeneth99 approved these changes

2023-02-28 17:57 UTC, yanukadeneth99 commented
These are great changes. Good stuff @jitendragangwar123! 🔥

2023-02-28 17:57 UTC, merged