fixed the typo errors
LearnWeb3DAO/Junior-Track pull request #25
Opened 2023-02-26 18:51 UTC by jitendragangwar123

I have fixed the typo errors. Please review and merge it.

2023-02-27 12:59 UTC, yanukadeneth99 requested changes

2023-02-27 12:59 UTC, yanukadeneth99 commented on Indexing-Contract-Data-TheGraph.md
> +Let's now write some code to query the graph, create a new folder inside your `my-app` folder and name it `queries`. Inside the `queries` folder create a new file named `index.js` and paste the follo
Could you change this line into -
`Let's write some code....`. 

So, basically removing the word `now`.

2023-02-27 16:10 UTC, jitendragangwar123 commented
I have updated the file according to the given suggestions. Please review and merge it.

2023-02-28 18:00 UTC, yanukadeneth99 commented
Nice work @jitendragangwar123!

2023-02-28 18:00 UTC, merged