Updated Docs
LearnWeb3DAO/Junior-Track pull request #32
Opened 2023-03-28 14:42 UTC by Shiva-Sai-ssb

I have included a npm command in the following documentations which is essential for Windows users; without it, users will encounter errors. As a Windows user, I have experienced this firsthand.

1. Etherscan-Verification.md
2. IPFS-Practical.md
3. Lottery-Game-Chainlink-VRF.md

2023-03-29 06:22 UTC, Shiva-Sai-ssb commented
@yanukadeneth99 Hi, is there a reason why you have not merged this pull request?

2023-03-29 09:20 UTC, yanukadeneth99 commented
Hi @Shiva-Sai-ssb I haven't had time to go through this PR yet. Will update here soon! 😄

2023-04-02 03:12 UTC, yanukadeneth99 requested changes

2023-04-02 03:12 UTC, yanukadeneth99 commented on Lottery-Game-Chainlink-VRF.md
> +npm install --save-dev @nomicfoundation/hardhat-toolbox
Let's move this line above the OpenZeppelin installation. Basically below the `...then follow the instructions on your terminal.` to that we keep things a bit organized.

2023-04-02 03:12 UTC, yanukadeneth99 commented on IPFS-Practical.md
> +npm install --save-dev @nomicfoundation/hardhat-toolbox
Let's move this line above the OpenZeppelin installation. Basically below the `...then follow the instructions on your terminal.` to that we keep things a bit organized.

2023-04-02 06:16 UTC, Shiva-Sai-ssb commented
@yanukadeneth99, made changes as requested.

2023-04-04 03:37 UTC, yanukadeneth99 commented
Looking great. Nice work @Shiva-Sai-ssb 😄

2023-04-04 03:37 UTC, merged